# Add configuration values here, as shown below.
#
#For Twitter:

twitter_consumer_key: "csHhdt4w49qwvpjP24tUuOPL4"
twitter_consumer_secret: "CLXHUaZ1Uk09Ec8EXsOD77NuWoAvur3SuwUfIg5dFxUIpZRuS5"
twitter_access_token: "859475169592606720-V0nwJVad4CFIoQIMOnVG4t0W7J0P7VW"
twitter_access_token_secret: "0vLJMMBOKaiNrbg2739r6xAnXesVHQNWgmWS7ntKv0LxH"

#For Facebook:

facebook_app_id: "1873963472816401"
facebook_app_secret: "8d9f5c33013ee314950eb4192b66d4a8"

google_client_id: "326988407465-uepga1ce8iaolm4m38ojl5m081qauvm9.apps.googleusercontent.com"
google_client_id_secret: "pIx3j8NyGPJXLD_TT2uYcxH1"

linkedin_client_id: "78jxqvm5h6fa8q"
linkedin_secret: "2Hyujwfqca4hiX9m"

github_client_id: "2e3976bce4036eda8c42"
github_client_secret: "b635698dbba1d32d216f539b3e17769acb290462"

TUMBLR_KEY: "FPgYKhhqzLAArup7200PAYo2mecBDg8KTEBW8UlWhHyevgyGW0"
TUMBLR_SECRET:  "T20XRtW9A0PfTWO6v2k93fAOXZU6iSSLJbiEsYWeunHbktby4J"

TWITCH_CLIENT_ID: "uj53o98rasdwbhwic692sh6jmd36w5"
TWITCH_CLIENT_SECRET: "ogxofm3kaex018rkdutev2gvi7188n"

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

send_mail_password: "letsget555robots"
